version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=LojaBD
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    restart: always

  web:
    image: brunobiazon/loja-suplementos:latest
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn loja.wsgi:application --bind 0.0.0.0:8000 --workers 2"
    volumes:
      - media_files:/app/media
      - static_files:/app/static
    env_file:
      - .env
    environment:
      - DB_NAME=LojaBD
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media_files:/app/media
      - static_files:/app/static
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  media_files:
  static_files: