# Generated by Django 6.0.3 on 2026-03-20 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nodescricao_longa',
            new_name='descricao_longa',
        ),
    ]
