# Generated by Django 6.0.3 on 2026-03-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_slug_alter_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='promocao_relampago',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='Não', max_length=1),
        ),
    ]
