# Generated by Django 6.0.3 on 2026-04-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_slug_alter_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Outro', 'Outro'), ('Whey', 'Whey Protein'), ('Saude', 'Saúde e Bem-estar'), ('Creatina', 'Creatina'), ('Snacks', 'Snacks/Lanches'), ('Pretreino', 'Pré-treino'), ('Termo', 'Termogênico'), ('Hiper', 'Hipercalórico'), ('Endurance', 'Endurance')], default='Outro', max_length=50),
        ),
        migrations.AddField(
            model_name='produto',
            name='promocao_relampago',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='N', max_length=1),
        ),
    ]
