# Generated by Django 6.0.3 on 2026-04-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_produto_categoria_produto_promocao_relampago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
