# Generated by Django 6.0.3 on 2026-04-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_produto_categoria_alter_produto_promocao_relampago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Outro', 'Outro'), ('Whey', 'Whey Protein'), ('Saude', 'Saúde e Bem-estar'), ('Creatina', 'Creatina'), ('Snacks', 'Snacks/Lanches'), ('Pretreino', 'Pré-treino'), ('Termo', 'Termogênico'), ('Hiper', 'Hipercalórico'), ('Endurance', 'Endurance')], default='Outro', max_length=50),
        ),
    ]
